{{ edit_comment_base }}

{% if 'supervisord' == php_type %}
FROM php:{{ php_version }}-cli-alpine
{% else %}
FROM php:{{ php_version }}-{{ php_type }}-alpine
{% endif %}

# Labels
# https://github.com/opencontainers/image-spec/blob/main/annotations.md
LABEL "maintainer"="lotyp <lotyp7@gmail.com>"
LABEL "vendor"="wayofdev"
LABEL "org.opencontainers.image.authors"="lotyp <lotyp7@gmail.com>"
LABEL "org.opencontainers.image.url"="https://hub.docker.com/r/wayofdev/php-{{ level }}"
LABEL "org.opencontainers.image.documentation"="https://github.com/wayofdev/docker-php-{{ level }}"
LABEL "org.opencontainers.image.source"="https://github.com/wayofdev/docker-php-{{ level }}"
LABEL "org.opencontainers.image.vendor"="wayofdev"
LABEL "org.opencontainers.image.licenses"="MIT"
LABEL "org.opencontainers.image.ref.name"="{{ php_version }}-{{ level }}"
LABEL "org.opencontainers.image.title"="PHP-{{ php_type|upper }} {{ php_version }}-{{ level }}"
LABEL "org.opencontainers.image.description"="PHP-{{ php_type|upper }} {{ php_version }}-{{ level }}"

ENV LANG="en_US.UTF-8"
ENV LC_ALL="en_US.UTF-8"
ENV LANGUAGE="en_US.UTF-8"

ENV PHP_OPCACHE_ENABLE="{{ settings_opcache_ini.php_opcache_enable }}"
ENV PHP_OPCACHE_ENABLE_CLI="{{ settings_opcache_ini.php_opcache_enable_cli }}"
ENV PHP_TIMEZONE="{{ settings_php_ini.php_timezone }}"
ENV PHP_POST_MAX_SIZE="{{ settings_php_ini.php_post_max_size }}"
ENV PHP_MEMORY_LIMIT="{{ settings_php_ini.php_memory_limit }}"
{% if php_type == 'fpm' %}
ENV PHPFPM_SLOWLOG_TIMEOUT="5s"
{% endif %}

COPY --chown=www-data ./configs/opcache.ini /usr/local/etc/php/conf.d/opcache.ini
COPY --chown=www-data ./configs/php.ini /usr/local/etc/php/conf.d/php.ini

RUN set -eux; \
    apk -U upgrade -a \
{% if 'supervisord' == php_type %}
    && apk add --no-cache supervisor \
{% endif %}
    && \
    curl -sSLf \
        -o /usr/local/bin/install-php-extensions \
        https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions \
    && chmod +x /usr/local/bin/install-php-extensions \
    && install-php-extensions \
{% for ext in (ext_native_enabled + ext_pecl_enabled) | unique | sort %}
        {{ ext }} \
{% endfor %}
    && install-php-extensions --cleanup \
    && rm -rf /var/cache/apk/* \
    && rm -rf /tmp/* \
    && rm -rf /var/log/* \
    && chown -R www-data:www-data /usr/local/etc/php/conf.d/ \
    && rm -rf /var/www/html \
    && mkdir /app \
    && chown www-data:www-data /app

{% if 'fpm' == php_type %}
COPY ./configs/php-fpm.d/ /usr/local/etc/php-fpm.d/
{% endif %}
{% if 'supervisord' == php_type %}
COPY --chown=www-data ./configs/supervisord.conf /etc/supervisord.conf
{% endif %}

WORKDIR /app

USER www-data

{% if 'supervisord' == php_type %}
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
{% endif %}
